# Generated by Django 4.2.7 on 2023-11-17 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_pokemon_evolution_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('colGrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_submissions', to='grid.grid')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.pokemon')),
                ('rowGrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_submissions', to='grid.grid')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submission_count', models.IntegerField(default=0)),
                ('colGrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col_pokemon_statistics', to='grid.grid')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.pokemon')),
                ('rowGrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_pokemon_statistics', to='grid.grid')),
            ],
            options={
                'unique_together': {('pokemon', 'rowGrid', 'colGrid', 'date')},
            },
        ),
    ]
