# Generated by Django 4.2.7 on 2023-11-18 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_submission_pokemonstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid',
            old_name='lengendary',
            new_name='legendary',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='lengendary',
            new_name='legendary',
        ),
        migrations.AddField(
            model_name='grid',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
