# Generated by Django 4.2.7 on 2023-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_rename_lengendary_grid_legendary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemonstatistics',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='colGrid',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='rowGrid',
        ),
        migrations.AddField(
            model_name='pokemonstatistics',
            name='grid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='grid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pokemonstatistics',
            unique_together={('pokemon', 'grid', 'date')},
        ),
        migrations.RemoveField(
            model_name='pokemonstatistics',
            name='colGrid',
        ),
        migrations.RemoveField(
            model_name='pokemonstatistics',
            name='rowGrid',
        ),
    ]
