# Generated by Django 4.2.7 on 2023-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_alter_pokemonstatistics_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
