# Generated by Django 4.2.7 on 2023-11-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_alter_submission_pokemon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonStatistics',
            new_name='PokemonStatistic',
        ),
    ]
