# Generated by Django 4.2.7 on 2023-11-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0010_alter_pokemonstatistic_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.IntegerField(default=0),
        ),
    ]
