# Generated by Django 4.2.7 on 2023-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0011_pokemon_pokedex_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
