# Generated by Django 4.2.7 on 2023-11-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0014_alter_grid_date_alter_pokemonstatistic_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonstatistic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(),
        ),
    ]
