# Generated by Django 4.2.7 on 2023-11-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0015_alter_pokemonstatistic_date_alter_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(),
        ),
    ]
