# Generated by Django 4.2.7 on 2023-12-02 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0016_alter_score_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('grid_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=9)),
            ],
        ),
    ]
