# Generated by Django 4.2.7 on 2023-12-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0017_archivedgrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='evolution_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grid',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grid',
            name='legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grid',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
