# Generated by Django 4.2.7 on 2023-12-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0018_alter_grid_evolution_stage_alter_grid_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
