# Generated by Django 4.2.7 on 2023-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0019_alter_grid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='date',
            field=models.DateField(),
        ),
    ]
