# Generated by Django 5.0 on 2023-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0020_alter_grid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedgrid',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemonstatistic',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
